// BGM Player - custom playlist order (Skai's order)
export const TRACKS = [
  { id: "bgm.menu3", title: "Beginning 2", artist: "C418", sec: 175 },
  { id: "bgm.menu2", title: "Moog City 2", artist: "C418", sec: 179 },
  { id: "bgm.menu1", title: "Mutation", artist: "C418", sec: 184 },
  { id: "bgm.menu4", title: "Floating Trees", artist: "C418", sec: 244 },
  { id: "bgm.calm1", title: "Minecraft", artist: "C418", sec: 254 },
  { id: "bgm.calm2", title: "Clark", artist: "C418", sec: 191 },
  { id: "bgm.calm3", title: "Sweden", artist: "C418", sec: 215 },
  { id: "bgm.hal1", title: "Subwoofer Lullaby", artist: "C418", sec: 208 },
  { id: "bgm.hal2", title: "Living Mice", artist: "C418", sec: 177 },
  { id: "bgm.hal3", title: "Haggstrom", artist: "C418", sec: 204 },
  { id: "bgm.hal4", title: "Danny", artist: "C418", sec: 254 },
  { id: "bgm.nuance1", title: "Key", artist: "C418", sec: 65 },
  { id: "bgm.nuance2", title: "Oxygene", artist: "C418", sec: 65 },
  { id: "bgm.piano1", title: "Dry Hands", artist: "C418", sec: 68 },
  { id: "bgm.piano2", title: "Wet Hands", artist: "C418", sec: 90 },
  { id: "bgm.piano3", title: "Mice on Venus", artist: "C418", sec: 281 },
  { id: "bgm.creative3", title: "Haunt Muskie", artist: "C418", sec: 360 },
  { id: "bgm.creative4", title: "Aria Math", artist: "C418", sec: 309 },
  { id: "bgm.creative5", title: "Dreiton", artist: "C418", sec: 496 },
  { id: "bgm.creative6", title: "Taswell", artist: "C418", sec: 514 },
  { id: "bgm.creative1", title: "Biome Fest", artist: "C418", sec: 377 },
  { id: "bgm.creative2", title: "Blind Spots", artist: "C418", sec: 331 },
  { id: "bgm.infinite_amethyst", title: "Infinite Amethyst", artist: "Lena Raine", sec: 271 },
  { id: "bgm.one_more_day", title: "One More Day", artist: "Lena Raine", sec: 278 },
  { id: "bgm.stand_tall", title: "Stand Tall", artist: "Lena Raine", sec: 308 },
  { id: "bgm.left_to_bloom", title: "Left to Bloom", artist: "Lena Raine", sec: 342 },
  { id: "bgm.ancestry", title: "Ancestry", artist: "Lena Raine", sec: 343 },
  { id: "bgm.wending", title: "Wending", artist: "Lena Raine", sec: 314 },
  { id: "bgm.floating_dream", title: "Floating Dream", artist: "Kumi Tanioka", sec: 206 },
  { id: "bgm.comforting_memories", title: "Comforting Memories", artist: "Kumi Tanioka", sec: 275 },
  { id: "bgm.an_ordinary_day", title: "An Ordinary Day", artist: "Kumi Tanioka", sec: 331 },
  { id: "bgm.firebugs", title: "Firebugs", artist: "Lena Raine", sec: 312 },
  { id: "bgm.aerie", title: "Aerie", artist: "Lena Raine", sec: 296 },
  { id: "bgm.labyrinthine", title: "Labyrinthine", artist: "Lena Raine", sec: 324 },
  { id: "bgm.bromeliad", title: "Bromeliad", artist: "Aaron Cherof", sec: 312 },
  { id: "bgm.crescent_dunes", title: "Crescent Dunes", artist: "Aaron Cherof", sec: 248 },
  { id: "bgm.echo_in_the_wind", title: "Echo in the Wind", artist: "Aaron Cherof", sec: 296 },
  { id: "bgm.featherfall", title: "Featherfall", artist: "Aaron Cherof", sec: 345 },
  { id: "bgm.watcher", title: "Watcher", artist: "Aaron Cherof", sec: 332 },
  { id: "bgm.puzzlebox", title: "Puzzlebox", artist: "Aaron Cherof", sec: 299 },
  { id: "bgm.deeper", title: "Deeper", artist: "Lena Raine", sec: 303 },
  { id: "bgm.eld_unknown", title: "Eld Unknown", artist: "Lena Raine", sec: 296 },
  { id: "bgm.endless", title: "Endless", artist: "Lena Raine", sec: 402 },
  { id: "bgm.komorebi", title: "komorebi", artist: "Kumi Tanioka", sec: 288 },
  { id: "bgm.pokopoko", title: "pokopoko", artist: "Kumi Tanioka", sec: 304 },
  { id: "bgm.yakusoku", title: "yakusoku", artist: "Kumi Tanioka", sec: 271 },
  { id: "bgm.lilypad", title: "Lilypad", artist: "Amos Roddy", sec: 235 },
  { id: "bgm.below_and_above", title: "Below and Above", artist: "Amos Roddy", sec: 212 },
  { id: "bgm.os_piano", title: "O's Piano", artist: "Amos Roddy", sec: 275 },
  { id: "bgm.broken_clocks", title: "Broken Clocks", artist: "Amos Roddy", sec: 213 },
  { id: "bgm.fireflies", title: "Fireflies", artist: "Amos Roddy", sec: 155 },
  { id: "bgm.memories", title: "Memories", artist: "fingerspit", sec: 245 },
  { id: "bgm.ebb", title: "Ebb", artist: "fingerspit", sec: 306 },
  { id: "bgm.home", title: "Home", artist: "fingerspit", sec: 380 },
  { id: "bgm.shores", title: "Shores", artist: "fingerspit", sec: 320 },
  { id: "bgm.nightly", title: "Nightly", artist: "fingerspit", sec: 302 },
  { id: "bgm.axolotl", title: "Axolotl", artist: "C418", sec: 303 },
  { id: "bgm.dragon_fish", title: "Dragon Fish", artist: "C418", sec: 373 },
  { id: "bgm.shuniji", title: "Shuniji", artist: "C418", sec: 244 },
  { id: "bgm.nether1", title: "Concrete Halls", artist: "C418", sec: 253 },
  { id: "bgm.nether2", title: "Dead Voxel", artist: "C418", sec: 295 },
  { id: "bgm.nether3", title: "Warmth", artist: "C418", sec: 238 },
  { id: "bgm.nether4", title: "Ballad of the Cats", artist: "C418", sec: 274 },
  { id: "bgm.chrysopoeia", title: "Chrysopoeia", artist: "Lena Raine", sec: 243 },
  { id: "bgm.rubedo", title: "Rubedo", artist: "Lena Raine", sec: 312 },
  { id: "bgm.so_below", title: "So Below", artist: "Lena Raine", sec: 319 },
  { id: "bgm.boss", title: "Boss", artist: "C418", sec: 346 },
  { id: "bgm.end", title: "The End", artist: "C418", sec: 903 },
  { id: "bgm.credits", title: "Alpha", artist: "C418", sec: 602 },
  { id: "bgm.rec13", title: "13", artist: "C418", sec: 178 },
  { id: "bgm.cat", title: "Cat", artist: "C418", sec: 185 },
  { id: "bgm.blocks", title: "Blocks", artist: "C418", sec: 345 },
  { id: "bgm.chirp", title: "Chirp", artist: "C418", sec: 185 },
  { id: "bgm.far", title: "Far", artist: "C418", sec: 174 },
  { id: "bgm.mall", title: "Mall", artist: "C418", sec: 197 },
  { id: "bgm.mellohi", title: "Mellohi", artist: "C418", sec: 96 },
  { id: "bgm.stal", title: "Stal", artist: "C418", sec: 150 },
  { id: "bgm.strad", title: "Strad", artist: "C418", sec: 188 },
  { id: "bgm.ward", title: "Ward", artist: "C418", sec: 251 },
  { id: "bgm.rec11", title: "11", artist: "C418", sec: 71 },
  { id: "bgm.wait", title: "Wait", artist: "C418", sec: 237 },
  { id: "bgm.pigstep", title: "Pigstep", artist: "Lena Raine", sec: 148 },
  { id: "bgm.otherside", title: "otherside", artist: "Lena Raine", sec: 195 },
  { id: "bgm.rec5", title: "5", artist: "Samuel Aberg", sec: 178 },
  { id: "bgm.creator", title: "Creator", artist: "Lena Raine", sec: 176 },
  { id: "bgm.creator_mb", title: "Creator (Music Box)", artist: "Lena Raine", sec: 73 },
  { id: "bgm.relic", title: "Relic", artist: "Aaron Cherof", sec: 219 },
  { id: "bgm.precipice", title: "Precipice", artist: "Aaron Cherof", sec: 299 },
  { id: "bgm.tears", title: "Tears", artist: "Amos Roddy", sec: 175 },
  { id: "bgm.lava_chicken", title: "Lava Chicken", artist: "Hyper Potions", sec: 135 },
  { id: "bgm.bounce", title: "Bounce", artist: "fingerspit", sec: 234 },
];